### ISSUE TITLE
Adição de lojas

### ISSUE THREAD

**Issue by igormp** [makers-brazil/awesome-maker-br#12]
Nome: TiggerCOMP
Link: http://tiggercomp.com.br/
Estado: SP
Cidade: São Paulo

Nome: Soldafria
Link: https://www.soldafria.com.br/
Estado: SP
Cidade: São Paulo

Nome: NefelTech
Link: https://www.nefeltech.com/
Estado PE
Cidade: Recife

**Comment by douglaszuqueto** [comment]
Adicionado :+1:
